![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [2]:
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [3]:
my_array = [0, 1, 2, 3, 4, 5, 6, 7, 8 ,9]

## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [6]:
import numpy as np

In [7]:
array_true = np.ones((3, 3), dtype=bool)

print(array_true)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [10]:
my_array = [0, 1, 2, 3, 4, 5, 6, 7, 8 ,9]

x = np.array([my_array])
impares = x(x%2!=0)

TypeError: 'numpy.ndarray' object is not callable

## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [2]:
my_array = [0, 1, 2, 3, 4, 5, 6, 7, 8 ,9]

x = np.array[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(np.where(x%2!=0, -1))

NameError: name 'np' is not defined

## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [ ]:
my_array = [0, 1, 2, 3, 4, 5, 6, 7, 8 ,9]

y = x.reshape((2,2))
print(y)

ValueError: cannot reshape array of size 10 into shape (5,5)

## Ejercicio 8
Concatena los siguientes arrays verticalmente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [4]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate([a,b], axis=0)

NameError: name 'np' is not defined

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [5]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate((a,b), axis=1)

NameError: name 'np' is not defined

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa la función `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [21]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento de `my_array`
3. Accede al último elemento de `my_array`
4. Imprime por pantalla los numeros del 1 al 7 de `my_array`

In [22]:
my_array = np.array[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

print(my_array[0])
print(my_array[-1])
print(np.arrange(7, 1, 1))

TypeError: 'builtin_function_or_method' object is not subscriptable

## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [ ]:
my_matrix = np.array([[1,2,3], 
                      [4,5,6], 
                      [7,8,9]])

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [ ]:
print(np.arange(1,50, 3))

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [28]:
print(np.arange(4, 1, -0.25, np.float32))

[4.   3.75 3.5  3.25 3.   2.75 2.5  2.25 2.   1.75 1.5  1.25]


## Ejercicio 16
Lee la imagen "numpy.png" usando Pillow, y guárdala en un array.

In [30]:
from PIL import Image
import matplotlib.pyplot as plt

In [31]:
imagen_pillow = Image.open('./img/numpy.png')
imagen = np.array(imagen_pillow)
print(type(imagen))

<class 'numpy.ndarray'>


## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [7]:
x = np.arrange(4, 1)

y = x.reshape((2, 2))
print(y)

NameError: name 'np' is not defined

## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [33]:
print(np.random.randint(4, size = (5, 3)))

[[3 3 1]
 [3 0 1]
 [3 2 2]
 [1 3 0]
 [3 2 1]]


## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

## Ejercicio 20
Dado el siguiente array

```Python
x = np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuánta es la longitud cada dimensión?

In [35]:
x = np.random.randint(10, 20, size = (5,2,6))
print(x)

[[[16 13 14 14 10 12]
  [19 16 15 17 15 11]]

 [[13 18 17 16 11 11]
  [18 14 15 15 10 10]]

 [[19 19 18 16 19 17]
  [14 15 12 14 13 19]]

 [[19 13 11 11 16 12]
  [10 18 19 15 16 18]]

 [[17 16 14 17 14 18]
  [16 17 14 17 10 11]]]
