![imagen](./img/ejercicios.png)

In [2]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden, usando numpy.

In [16]:
my_array = np.arange(10)
print(my_array)
my_array[my_array%2==1]
orden = np.sort(my_array)
print(orden)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [17]:
print(np.my_array(-2,-3))

AttributeError: module 'numpy' has no attribute 'my_array'

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [18]:
print(np.my_array(0,2,-1))

AttributeError: module 'numpy' has no attribute 'my_array'

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [22]:
a = np.arange(20).reshape(4, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [25]:
np.transpose(a)

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [31]:
matriz_5 = a[1:2, 2:4]
print(matriz_5)

[[7 8]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [33]:
matriz_6 = a[1:4, 3:6]
print(matriz_6)

[[ 8  9]
 [13 14]
 [18 19]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [35]:
matriz_7 = a[1:5, 2:5]
print(matriz_7)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [36]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
filtro_1 = x =="Loro" 
print(filtro_1)

[ True False False  True False]


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [42]:
secuencia = np.arange(20)
print(secuencia)

y = secuencia.reshape((2,10))
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [45]:
array_10 = np.zeros(10)
print(array_10)
array_10.nbytes

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


80

In [46]:
array_10[3]=1
print(array_10)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [51]:
vector = np.arange(10,50)
print(vector)

invertido = np.flip(vector)
print(invertido)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [57]:
vector = [1, 2, 0, 0, 4, 0]

def indices_no_cero(vector):
    return [i for i, w in enumerate(vector) if x != 0]
print(w)


NameError: name 'w' is not defined

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [63]:
x = np.random.randint(10, 10)
print(x)

ValueError: low >= high

## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [ ]:
vector14 = np.random.rand(30)
media = np.mean(vector14)
print(vector14)
print(media)

[0.87454848 0.44585727 0.41688495 0.68696912 0.21506023 0.20732515
 0.70988587 0.02496039 0.687311   0.3152     0.08175967 0.58209581
 0.46886658 0.20019187 0.46648924 0.0579616  0.21355214 0.02579781
 0.47514507 0.52742431 0.38175189 0.84709026 0.66972506 0.14852646
 0.35064096 0.62115821 0.18658078 0.97632148 0.76296386 0.94761426]
0.45252199238794977


: 

## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8